//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace wsCipolServices.Fachada.Seguridad.CipolSupervision {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsCipolSupervisionSoap", Namespace="http://RGP/CIPOL/wsCipolSupervision")]
    public partial class wsCipolSupervision : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidarSupervisorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarSupervisorConAuditoriaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsCipolSupervision() {
            this.Url = global::wsCipolServices.Properties.Settings.Default.wsCipolServices_Fachada_Seguridad_CipolSupervision_wsCipolSupervision;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidarSupervisorCompletedEventHandler ValidarSupervisorCompleted;
        
        /// <remarks/>
        public event ValidarSupervisorConAuditoriaCompletedEventHandler ValidarSupervisorConAuditoriaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://RGP/CIPOL/wsCipolSupervision/ValidarSupervisor", RequestNamespace="http://RGP/CIPOL/wsCipolSupervision", ResponseNamespace="http://RGP/CIPOL/wsCipolSupervision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidarSupervisor(string Usuario, string Clave) {
            object[] results = this.Invoke("ValidarSupervisor", new object[] {
                        Usuario,
                        Clave});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarSupervisorAsync(string Usuario, string Clave) {
            this.ValidarSupervisorAsync(Usuario, Clave, null);
        }
        
        /// <remarks/>
        public void ValidarSupervisorAsync(string Usuario, string Clave, object userState) {
            if ((this.ValidarSupervisorOperationCompleted == null)) {
                this.ValidarSupervisorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarSupervisorOperationCompleted);
            }
            this.InvokeAsync("ValidarSupervisor", new object[] {
                        Usuario,
                        Clave}, this.ValidarSupervisorOperationCompleted, userState);
        }
        
        private void OnValidarSupervisorOperationCompleted(object arg) {
            if ((this.ValidarSupervisorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarSupervisorCompleted(this, new ValidarSupervisorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://RGP/CIPOL/wsCipolSupervision/ValidarSupervisorConAuditoria", RequestNamespace="http://RGP/CIPOL/wsCipolSupervision", ResponseNamespace="http://RGP/CIPOL/wsCipolSupervision", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidarSupervisorConAuditoria(string Usuario, string Clave, int IDUsuarioSupervisor, int IDUsuario, int IDTareaSupervisar, string Terminal) {
            object[] results = this.Invoke("ValidarSupervisorConAuditoria", new object[] {
                        Usuario,
                        Clave,
                        IDUsuarioSupervisor,
                        IDUsuario,
                        IDTareaSupervisar,
                        Terminal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarSupervisorConAuditoriaAsync(string Usuario, string Clave, int IDUsuarioSupervisor, int IDUsuario, int IDTareaSupervisar, string Terminal) {
            this.ValidarSupervisorConAuditoriaAsync(Usuario, Clave, IDUsuarioSupervisor, IDUsuario, IDTareaSupervisar, Terminal, null);
        }
        
        /// <remarks/>
        public void ValidarSupervisorConAuditoriaAsync(string Usuario, string Clave, int IDUsuarioSupervisor, int IDUsuario, int IDTareaSupervisar, string Terminal, object userState) {
            if ((this.ValidarSupervisorConAuditoriaOperationCompleted == null)) {
                this.ValidarSupervisorConAuditoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarSupervisorConAuditoriaOperationCompleted);
            }
            this.InvokeAsync("ValidarSupervisorConAuditoria", new object[] {
                        Usuario,
                        Clave,
                        IDUsuarioSupervisor,
                        IDUsuario,
                        IDTareaSupervisar,
                        Terminal}, this.ValidarSupervisorConAuditoriaOperationCompleted, userState);
        }
        
        private void OnValidarSupervisorConAuditoriaOperationCompleted(object arg) {
            if ((this.ValidarSupervisorConAuditoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarSupervisorConAuditoriaCompleted(this, new ValidarSupervisorConAuditoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ValidarSupervisorCompletedEventHandler(object sender, ValidarSupervisorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarSupervisorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarSupervisorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void ValidarSupervisorConAuditoriaCompletedEventHandler(object sender, ValidarSupervisorConAuditoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarSupervisorConAuditoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarSupervisorConAuditoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591