<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="UITreeViewTareasDisponiblesUC.ascx.cs"
    Inherits="COA.WebCipol.Presentacion.UIControlsHelper.TreeView.UITreeViewTareasDisponiblesUC" %>
<div id="dv" runat="Server" style="overflow: scroll; height: 400px;">
    <asp:TreeView ID="tv" runat="server" ImageSet="Simple" NodeIndent="10" 
        AutoGenerateDataBindings="False" 
        EnableViewState="False">
    </asp:TreeView>
</div>
