//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace wsCipolServices.Fachada.Seguridad.ABM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsCOA_ABMBaseSoap", Namespace="http://WSCOA_ABMBASE")]
    public partial class wsCOA_ABMBase : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EstablecerConexionActivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RecuperarOperationCompleted;
        
        private System.Threading.SendOrPostCallback GrabarOperationCompleted;
        
        private System.Threading.SendOrPostCallback FechaServidorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsCOA_ABMBase() {
            this.Url = global::wsCipolServices.Properties.Settings.Default.wsCipolServices_Fachada_Seguridad_ABM_wsCOA_ABMBase;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EstablecerConexionActivaCompletedEventHandler EstablecerConexionActivaCompleted;
        
        /// <remarks/>
        public event RecuperarCompletedEventHandler RecuperarCompleted;
        
        /// <remarks/>
        public event GrabarCompletedEventHandler GrabarCompleted;
        
        /// <remarks/>
        public event FechaServidorCompletedEventHandler FechaServidorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WSCOA_ABMBASE/EstablecerConexionActiva", RequestNamespace="http://WSCOA_ABMBASE", ResponseNamespace="http://WSCOA_ABMBASE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EstablecerConexionActiva(string IDConexion) {
            object[] results = this.Invoke("EstablecerConexionActiva", new object[] {
                        IDConexion});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EstablecerConexionActivaAsync(string IDConexion) {
            this.EstablecerConexionActivaAsync(IDConexion, null);
        }
        
        /// <remarks/>
        public void EstablecerConexionActivaAsync(string IDConexion, object userState) {
            if ((this.EstablecerConexionActivaOperationCompleted == null)) {
                this.EstablecerConexionActivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstablecerConexionActivaOperationCompleted);
            }
            this.InvokeAsync("EstablecerConexionActiva", new object[] {
                        IDConexion}, this.EstablecerConexionActivaOperationCompleted, userState);
        }
        
        private void OnEstablecerConexionActivaOperationCompleted(object arg) {
            if ((this.EstablecerConexionActivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstablecerConexionActivaCompleted(this, new EstablecerConexionActivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WSCOA_ABMBASE/Recuperar", RequestNamespace="http://WSCOA_ABMBASE", ResponseNamespace="http://WSCOA_ABMBASE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet Recuperar(string NombreTabla) {
            object[] results = this.Invoke("Recuperar", new object[] {
                        NombreTabla});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void RecuperarAsync(string NombreTabla) {
            this.RecuperarAsync(NombreTabla, null);
        }
        
        /// <remarks/>
        public void RecuperarAsync(string NombreTabla, object userState) {
            if ((this.RecuperarOperationCompleted == null)) {
                this.RecuperarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRecuperarOperationCompleted);
            }
            this.InvokeAsync("Recuperar", new object[] {
                        NombreTabla}, this.RecuperarOperationCompleted, userState);
        }
        
        private void OnRecuperarOperationCompleted(object arg) {
            if ((this.RecuperarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RecuperarCompleted(this, new RecuperarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WSCOA_ABMBASE/Grabar", RequestNamespace="http://WSCOA_ABMBASE", ResponseNamespace="http://WSCOA_ABMBASE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Grabar(System.Data.DataSet Dataset, string NombreTabla, TipoProceso TipoProceso) {
            object[] results = this.Invoke("Grabar", new object[] {
                        Dataset,
                        NombreTabla,
                        TipoProceso});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GrabarAsync(System.Data.DataSet Dataset, string NombreTabla, TipoProceso TipoProceso) {
            this.GrabarAsync(Dataset, NombreTabla, TipoProceso, null);
        }
        
        /// <remarks/>
        public void GrabarAsync(System.Data.DataSet Dataset, string NombreTabla, TipoProceso TipoProceso, object userState) {
            if ((this.GrabarOperationCompleted == null)) {
                this.GrabarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGrabarOperationCompleted);
            }
            this.InvokeAsync("Grabar", new object[] {
                        Dataset,
                        NombreTabla,
                        TipoProceso}, this.GrabarOperationCompleted, userState);
        }
        
        private void OnGrabarOperationCompleted(object arg) {
            if ((this.GrabarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GrabarCompleted(this, new GrabarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://WSCOA_ABMBASE/FechaServidor", RequestNamespace="http://WSCOA_ABMBASE", ResponseNamespace="http://WSCOA_ABMBASE", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime FechaServidor() {
            object[] results = this.Invoke("FechaServidor", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public void FechaServidorAsync() {
            this.FechaServidorAsync(null);
        }
        
        /// <remarks/>
        public void FechaServidorAsync(object userState) {
            if ((this.FechaServidorOperationCompleted == null)) {
                this.FechaServidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFechaServidorOperationCompleted);
            }
            this.InvokeAsync("FechaServidor", new object[0], this.FechaServidorOperationCompleted, userState);
        }
        
        private void OnFechaServidorOperationCompleted(object arg) {
            if ((this.FechaServidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FechaServidorCompleted(this, new FechaServidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WSCOA_ABMBASE")]
    public enum TipoProceso {
        
        /// <remarks/>
        Insertar,
        
        /// <remarks/>
        Eliminar,
        
        /// <remarks/>
        Actualizar,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void EstablecerConexionActivaCompletedEventHandler(object sender, EstablecerConexionActivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstablecerConexionActivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstablecerConexionActivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void RecuperarCompletedEventHandler(object sender, RecuperarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RecuperarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RecuperarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void GrabarCompletedEventHandler(object sender, GrabarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GrabarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GrabarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void FechaServidorCompletedEventHandler(object sender, FechaServidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FechaServidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FechaServidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.DateTime Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591