-- PARA ORACLE: 
--  Remover SET NOCOUNT ON, SET NOCOUNT OFF, reemplazar GETDATE() por SYSDATE.
--  Utilizar los inserts de SE_HISTORIAL_USUARIO para oracle, ver mas abajo.

SET NOCOUNT ON
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_AUTORIZACION
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_AUTORIZACION (IDAUTORIZACION,CODAUTORIZ,DESCAUTORIZ)VALUES(0,'S/A','Tareas Primitivas sin autorización');
INSERT INTO SE_AUTORIZACION (IDAUTORIZACION,CODAUTORIZ,DESCAUTORIZ)VALUES(1,'1A','Tareas Primitivas que requieren 1 Autorizante');
INSERT INTO SE_AUTORIZACION (IDAUTORIZACION,CODAUTORIZ,DESCAUTORIZ)VALUES(2,'2/A','Tareas Primitivas que requieren 2 Autorizantes');
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_MENUES
-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------
-- Tabla SIST_KDOCUMENTOS
-------------------------------------------------------------------------------------------------------------
INSERT INTO SIST_KDOCUMENTOS (IDTIPODOC,TIPODOCUMENTO,TIPOABREVIADO,DOCBAJA)VALUES(0,'NO ESPECIFICADO','N/A','N');
-------------------------------------------------------------------------------------------------------------
-- Tabla SIST_KAREAS
-------------------------------------------------------------------------------------------------------------
INSERT INTO SIST_KAREAS (IDAREA,NOMBREAREA,RESPONSABLE,CARGORESPONSABLE,COMENTARIOS,BAJA,FICTICIA)VALUES(0,' NO ESPECIFICADA','','','  NO ESPECIFICADA','N','N');
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_GRUPO_TAREA
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_GRUPO_TAREA (IDGRUPO,DESCGRUPO)VALUES(0,'GRUPO RAIZ');
INSERT INTO SE_GRUPO_TAREA (IDGRUPO,DESCGRUPO)VALUES(1,'SIR - Seguridad');
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_CODAUDITORIA
-------------------------------------------------------------------------------------------------------------
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(100,'Intento de uso de la terminal @ ,no habilitada para el uso de la aplicación');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(110,'El usuario inexistente @, efectuó un intento de inicio de sesión en la terminal @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(120,'El usuario @ posee un bloqueo generado por exceso de intentos de inicio de sesión con contraseña inválida');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(130,'El usuario @ posee un bloqueo generado por procesos de seguridad');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(140,'El usuario @ intentó iniciar una sesión con una contraseña inválida');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(150,'El usuario @ provocó el bloqueo de su cuenta debido al exceso de intentos de inicio de sesión con contraseña inválida');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(160,'El usuario @ respondió afirmativamente a la propuesta anticipada de cambio de contraseña por vencimiento cercano');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(170,'El usuario @ comenzó el proceso de cambio de contraseña debido al vencimiento de la misma');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(180,'El usuario @ especificó una contraseña anterior inválida cuando efectuaba el proceso de cambio de la misma');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(190,'El usuario @ especificó una dupla de contraseñas que no son coincidentes, cuando efectuaba el proceso de cambio de la misma');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(200,'La longitud de la nueva contraseña especificada por el usuario @ no cumple con la longitud mínima requerida');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(205,'El nivel de complejidad de la nueva contraseña especificada por el usuario @ no cumple con el  establecido en la política');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(210,'Se rechazó la nueva contraseña propuesta por el usuario @ debido a la existencia de la misma en el archivo histórico');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(220,'Se rechazó el intento de inicio de sesión del usuario @ debido a que su contraseña ha caducado');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(230,'Se rechazó el intento de inicio de sesión del usuario @ debido a que no está autorizado para el uso de la terminal @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(240,'Se rechazó el intento de inicio de sesión del usuario @ debido a la restricción horaria que posee');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(250,'Se rechazó el intento de inicio de sesión del usuario @ en la terminal @ debido a que ya posee otra sesión activa');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(260,'En la terminal @ se especificó una contraseña errónea para el usuario autorizante @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(270,'En la terminal @ se ha excedido la cantidad de intentos fallidos al especificar la contraseña  el usuario autorizante @. Se canceló la tarea involucrada.');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(400,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó el cambio de la cantidad de tiempo para bloqueo de terminal por inactividad. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(410,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó el cambio de la cantidad de intentos de inicio de sesión inválidos admitidos. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(420,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, modificó la cantidad de tiempo a partir de la cual se desbloquean las cuentas de usuario. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(430,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó el cambio de la longitud mínima de contraseñas. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(440,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó el cambio de la duración máxima de las contraseñas. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(450,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó el cambio de la duración mínima de las contraseñas. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(460,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó el cambio de la cantidad de días de antelación para aviso de próximo vencimiento de la contraseña de usuario. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(470,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en la cantidad de contraseñas que se almacenan para control de repetición. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(480,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en la cantidad de días admitidos sin inicio de sesión. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(490,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en la cantidad de minutos de prórroga para el horario de los usuarios. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(500,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en la cantidad de minutos de antelación para el aviso de finalización del horario admitido. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(510,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en la cantidad de minutos para bloquear el panel de ejecución por inactividad. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(520,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en el modo de asignación de tareas y roles. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(530,'El usuario @ en el contexto de administrador de la seguridad desde la PC @, efectuó la modificación en el nivel de complejidad exigido para la contraseña. Valor existente: @, nuevo valor: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(600,'El usuario @ en el contexto de administrador de la seguridad, efectuó el desbloqueo de la cuenta del usuario @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(610,'El usuario @ en el contexto de administrador de la seguridad, efectuó el bloqueo de la cuenta del usuario @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(620,'El usuario @ en el contexto de administrador de la seguridad, efectuó el cambio de la contraseña del usuario @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(700,'El usuario @ en el contexto de administrador de la seguridad, efectuó un ABM de grupos de exclusión');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(710,'El usuario @ en el contexto de administrador de la seguridad, efectuó un ABM de roles');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(720,'El usuario @ en el contexto de administrador de la seguridad, efectuó un ABM de tareas de autorización');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(730,'El usuario @ en el contexto de administrador de la seguridad, efectuó modificaciones en las pertenencias de tareas a los grupos de exclusión');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(740,'El usuario @ en el contexto de administrador de la seguridad, efectuó modificaciones en las pertenencias de tareas a los roles');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(750,'El usuario @ en el contexto de administrador de la seguridad, efectuó el alta del usuario: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(760,'El usuario @ en el contexto de administrador de la seguridad, efectuó la baja del usuario: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(770,'El usuario @ en el contexto de administrador de la seguridad, efectuó cambios en los roles asociados al usuario: @');
INSERT INTO [se_codauditoria] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(780,'El usuario @ en el contexto de administrador de la seguridad, efectuó la activación del usuario: @');
-- 25-04-2014 EmilianoD: GCPCambiosWeb: 15293 Agregar registro de LOGIN/LOGOUT al aplicativo
INSERT INTO [SE_CODAUDITORIA] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(0,'El usuario @ realizo el login desde la terminal @');
INSERT INTO [SE_CODAUDITORIA] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(790,'El usuario @ realizo el cierre de sesión desde (@ - @).');
INSERT INTO [SE_CODAUDITORIA] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(1,'El usuario @ realizo el logout desde la terminal @');
INSERT INTO [SE_CODAUDITORIA] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(2,'Se cerró la sesión en la terminal @ por superar el límite de tiempo permitido');
INSERT INTO [SE_CODAUDITORIA] ([CODAUDITORIA],[TEXTOAUDITORIA])VALUES(3,'El usuario @ cerró involuntariamente la sesión en la terminal @');

-------------------------------------------------------------------------------------------------------------
-- Tabla SE_MENSAJES
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(0,'Proceso exitoso.');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(10,'Terminal bloqueada. Consulte al administrador del sistema');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(15,'Terminal no habilitada. Consulte al administrador del sistema');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(17,'Imposible iniciar una sesión para el usuario especificado');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(18,'El usuario tiene una sesión iniciada en la terminal @. Imposible continuar');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(20,'No se puede iniciar la sesión. Verifique la cuenta y la contraseña y reintente, si no es posible nuevamente consulte al administrador');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(25,'Falta 1 día para que caduque su contraseña. ¿Desea efectuar ahora la renovación?');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(30,'Faltan @ días para que caduque su contraseña. ¿Desea efectuar ahora la renovación?');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(35,'La contraseña ha caducado, a continuación comenzará el proceso de renovación');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(40,'Usuario no autorizado para el uso de esta terminal. Consulte al administrador del sistema');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(45,'Horario de trabajo no autorizado para el usuario especificado. Consulte al administrador del sistema');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(50,'La contraseña especificada no cumple los requisitos establecidos');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(55,'No hay coincidencia entre la nuevas contraseñas  indicadas. Ingréselas nuevamente');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(60,'El administrador ha forzado el cambio de contraseña. A continuación comenzará el proceso');
INSERT INTO SE_MENSAJES (CODMENSAJE,TEXTOMENSAJE)VALUES(100,'Contraseña incorrecta para el usuario autorizante especificado. Verifique y reintente.');
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_Parametros
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_Parametros (COLUMNA1,COLUMNA2,COLUMNA3,COLUMNA4,COLUMNA5)VALUES(NULL,NULL,NULL,'XVAJy3tM4Wlf9UyqyLRY3hVL1FYQPNc3aHslt/pIsgu0u8ws4yIm1IsCRhLs0XdqGnlL/8KYxJEc7WZOXlSKBNRdFKttPlya','dcEyNHR0CRI=');
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_USUARIOS
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_USUARIOS (IDUSUARIO,USUARIO,NOMBRES,DOMICILIO,FECHAULTUSOCTA,NRODOCUMENTO,CANTINTINVUSOCTA,FORZARCAMBIO,CTABLOQUEADA,COMENTARIO,FECHABLOQUEO,FECHAALTA,FECHABAJA,IDAREA,IDTIPODOC,ULTIMOSISTEMA,ALIAS_USUARIO,IDUSRALTA,IDUSRBAJA,EMAIL)
VALUES(0,'master','SuperUsuario','',GETDATE(),'','WuMtVHk8o#U=','iHLrZpbUtT8=','iHLrZpbUtT8=','',NULL,GETDATE(),NULL,0,0,NULL,'',0,NULL,NULL);
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_HORARIOS_USUARIO
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(1,0,23);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(2,0,23);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(3,0,23);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(4,0,23);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(5,0,23);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(6,0,23);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,0);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,1);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,2);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,3);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,4);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,5);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,6);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,7);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,8);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,9);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,10);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,11);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,12);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,13);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,14);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,15);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,16);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,17);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,18);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,19);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,20);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,21);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,22);
INSERT INTO SE_HORARIOS_USUARIO (IDDIA,IDUSUARIO,IDHORARIO)VALUES(7,0,23);
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_SIST_HABILITADOS
-------------------------------------------------------------------------------------------------------------
--[LeandroF]	21/09/2015 - TFS-WorkItem: 4974
INSERT INTO SE_SIST_HABILITADOS (IDSISTEMA,CODSISTEMA,DESCSISTEMA,FECHAHABILITACION,NOMBREEXEC,SISTEMAHABILITADO,ICONO,OBSERVACIONES,PAGINAPORDEFECTO,DESCRIPCIONCORTA,IMPACTACAJA)VALUES(1,'Seguridad','Sistema de Seguridad',GETDATE(),NULL,'S','icon-locked*blue','uvFHCab2NYhgd4#xNGFYJCxloC8kwlUY','','','');
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_HISTORIAL_USUARIO
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_HISTORIAL_USUARIO (IDUSUARIO,ORDEN,FECHAULTACT,FECHAVENCIMIENTO,SINONIMO)VALUES(0,0,GETDATE(),GETDATE(),'dvNTtGmZsDmup6P2YP/Dv2Au7eM=');
INSERT INTO SE_HISTORIAL_USUARIO (IDUSUARIO,ORDEN,FECHAULTACT,FECHAVENCIMIENTO,SINONIMO)VALUES(0,1,GETDATE(),GETDATE(),'OJBcKiPkBqQM7qlJohGrx6Ns7VM=');
INSERT INTO SE_HISTORIAL_USUARIO (IDUSUARIO,ORDEN,FECHAULTACT,FECHAVENCIMIENTO,SINONIMO)VALUES(0,2,GETDATE(),GETDATE(),'OucZFRq60eDKN005n2UoJQXwuDE=');

/* PARA ORACLE
INSERT INTO SE_HISTORIAL_USUARIO (IDUSUARIO,ORDEN,FECHAULTACT,FECHAVENCIMIENTO,SINONIMO)VALUES(0,0,to_date('12/03/2008 1:41:41','MM/DD/YYYY HH24:MI:SS'),TO_DATE('02/01/2009 1:41:41','MM/DD/YYYY HH24:MI:SS'),'dvNTtGmZsDmup6P2YP/Dv2Au7eM=');
INSERT INTO SE_HISTORIAL_USUARIO (IDUSUARIO,ORDEN,FECHAULTACT,FECHAVENCIMIENTO,SINONIMO)VALUES(0,1,to_date('12/03/2008 1:41:26','MM/DD/YYYY HH24:MI:SS'),TO_DATE('02/01/2009 1:41:26','MM/DD/YYYY HH24:MI:SS'),'OJBcKiPkBqQM7qlJohGrx6Ns7VM=');
INSERT INTO SE_HISTORIAL_USUARIO (IDUSUARIO,ORDEN,FECHAULTACT,FECHAVENCIMIENTO,SINONIMO)VALUES(0,2,to_date('12/03/2008 1:41:13','MM/DD/YYYY HH24:MI:SS'),TO_DATE('02/01/2009 1:41:13','MM/DD/YYYY HH24:MI:SS'),'OucZFRq60eDKN005n2UoJQXwuDE=');
*/

-------------------------------------------------------------------------------------------------------------
-- Tabla SE_TAREAS
-------------------------------------------------------------------------------------------------------------
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1001,'SE1','Administración de Usuarios','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1002,'SE2','Administración de Roles','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1003,'SE3','Habilitación de Terminales operativas','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1004,'SE4','Agrupamiento de Tareas','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1005,'SE5','Definición de Políticas generales','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1006,'SE6','Tareas Autorizantes','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1007,'SE7','Monitor de Actividades','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1009,'SE9','Ver Reportes','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1010,'SE10','Ver Registros de Auditoría','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1011,'SE11','Administración de Areas','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1012,'SE12','Administración de Sistemas Bloqueados','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1013,'SE13','Activar Usuario','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1014,'SE14','Administración de Sistemas','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1015,'SE15','Administración de Tareas Primitivas','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1016,'SE16','Análisis de Auditoría','MA4phPHBUyA=',0,1,0);
INSERT INTO SE_TAREAS (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1017,'SE17','Cambiar Dominio y Organización','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1020,'SE20','Administración de Usuarios - Ocultar Botón Nuevo Usuario','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1021,'SE21','Administración de Usuarios - Ocultar Botón Modificar Usuario','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1022,'SE22','Administración de Usuarios - Ocultar Botón Eliminar Usuario','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1023,'SE23','Administración de Usuarios - Ocultar Botón Terminales Usuario','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1024,'SE24','Administración de Usuarios - Ocultar Botón Horarios Usuario','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1025,'SE25','Administración de Usuarios - Ocultar Botón Agregar Rol','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1026,'SE26','Administración de Usuarios - Ocultar Botón Quitar Rol','MA4phPHBUyA=',0,1,0);
INSERT INTO se_tareas (IDTAREA,CODIGOTAREA,DESCRIPCIONTAREA,REQUIEREAUDITORIA,IDAUTORIZACION,IDSISTEMA,IDGRUPO)VALUES(1027,'SE27','Administración de Usuarios - No Modificar Usuarios con tareas de CIPOL','MA4phPHBUyA=',0,1,0);
-------------------------------------------------------------------------------------------------------------
-- Tabla SE_ATRIBUTOSTAREAS
-------------------------------------------------------------------------------------------------------------
-- para que inicialice CIPOL y pida modo de Autenticación
update se_sist_habilitados set observaciones = 'byxqrZ9hQqI=' where idsistema = 1

IF NOT EXISTS(SELECT * FROM SE_MENSAJES WHERE CODMENSAJE = 4)
BEGIN
	INSERT INTO [SE_MENSAJES] (CODMENSAJE, TEXTOMENSAJE)
	VALUES (4, 'Ya posee una sesión activa. Para continuar debe cerrar la sesión anterior.')
END

IF NOT EXISTS(SELECT * FROM SE_CODAUDITORIA WHERE CODAUDITORIA = 4)
BEGIN
	INSERT INTO [SE_CODAUDITORIA] (CODAUDITORIA, TEXTOAUDITORIA)
	VALUES (4, 'Intento de Login. Se detecto una sesión activa para el usuario @')
END

/*
Para CIPOLWEB es necesario setear bien la PAGINAPORDEFECTO
UPDATE SE_SIST_HABILITADOS
	SET PAGINAPORDEFECTO = 'http://server14/WEBCIPOL/SISTEMASEGURIDAD/frmInicio.aspx'
	WHERE IDSISTEMA = 1

*/
SET NOCOUNT OFF