//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsCipolServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59859/wsInicioSesion.asmx")]
        public string wsCipolServices_Fachada_Seguridad_IniciarSesion_wsInicioSesion {
            get {
                return ((string)(this["wsCipolServices_Fachada_Seguridad_IniciarSesion_wsInicioSesion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59859/wsCOA_ABMBase.asmx")]
        public string wsCipolServices_Fachada_Seguridad_ABM_wsCOA_ABMBase {
            get {
                return ((string)(this["wsCipolServices_Fachada_Seguridad_ABM_wsCOA_ABMBase"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59859/wsInicioSesion_Java.asmx")]
        public string wsCipolServices_Fachada_Seguridad_InicioSesion_Java_wsInicioSesion_Java {
            get {
                return ((string)(this["wsCipolServices_Fachada_Seguridad_InicioSesion_Java_wsInicioSesion_Java"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59859/wsSeguridad.asmx")]
        public string wsCipolServices_Fachada_Seguridad_wsSeguridad {
            get {
                return ((string)(this["wsCipolServices_Fachada_Seguridad_wsSeguridad"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59859/wsSIRActualizaciones.asmx")]
        public string wsCipolServices_Fachada_Seguridad_Downloader_wsSIRActualizaciones {
            get {
                return ((string)(this["wsCipolServices_Fachada_Seguridad_Downloader_wsSIRActualizaciones"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:59859/wsCipolSupervision.asmx")]
        public string wsCipolServices_Fachada_Seguridad_CipolSupervision_wsCipolSupervision {
            get {
                return ((string)(this["wsCipolServices_Fachada_Seguridad_CipolSupervision_wsCipolSupervision"]));
            }
        }
    }
}
